services:
  awesome-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Set to true to include pre-built database in image
        # Set to false to mount database at runtime
        INCLUDE_DATABASE: false
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      # Mount SQLite database directory (used when INCLUDE_DATABASE=false)
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
